### ISSUE TITLE
there is no reactor running, must be called from the context of a Tokio 1.x runtime

### ISSUE THREAD

**Issue by z330789559** [rkudryashov/graphql-rust-demo#2]
sys: mac os
step:
 1.  clone git 
 2. config env
 3. cargo run --package planets-service --bin planets-service
 4. visit http://127.0.0.1:8001/
 5.  input params 
          subscription {
            latestPlanet {
              id
              name
              type
              details {
                meanRadius
              }
            }
          }
 error: thread 'actix-rt:worker:6' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'

**Comment by rkudryashov** [comment]
Hi @z330789559 

Can't guess by what it was caused, but could you try to launch Rust services as was said in the article (https://romankudryashov.com/blog/2020/12/graphql-rust/#_project_launch_and_api_testing)? Just use `cargo run` inside directory of the service.

Also, do you have any changes in the project compared with the latest version of the project? If so, you could try to reset those changes.

Also, you could start the project with Docker locally. If it will work without errors, then perhaps the error was caused by local environment.
