### ISSUE TITLE
The response time of "Login", "CreateUser" function is much higher than other functions like "GetSatellites", "GetPlanets"

### ISSUE THREAD

**Issue by hainghia** [rkudryashov/graphql-rust-demo#4]
![ping](https://user-images.githubusercontent.com/38345392/218613697-b89247e3-029d-4933-896c-10c4fa3aef32.png)
### The response time of "Login", "CreateUser" function is much higher than other functions like "GetSatellites", "GetPlanets"

- When I execute the command GraphQL: mutation CreateUser: Ping 515ms

```json
mutation CreateUser($user: UserInput!) {
  createUser(user: $user) {
    firstName
    lastName
    username
    role
  }
}
```

- When I execute the command GraphQL: mutation CreateUser: Ping 46ms

```json
query GetSatellites {
  getSatellites{
    id
    name
    lifeExists
    firstSpacecraftLandingDate
  }
}
```
I have a feeling but the function that needs to validate the Token has a much higher response time than the function that doesn't need to authenticate, please help me.

**Comment by rkudryashov** [comment]
In general, this is because of the operations performed under the hood on the server: SQL insert in case of `CreateUser` and JWT generation in case of `Login`.

> The response time of "Login", "CreateUser" function is much higher than other functions like "GetSatellites", "GetPlanets"

First, let's compare `GetSatellites` and `GetPlanets` vs `CreateUser`. In general, SQL writing operations are slower than reading (because the writing do multiple things under the hood that are not performed in reading queries).

Also, could you try to execute `CreateUser` 3-4 times consequently? It may turn out that its first execution has the biggest time.

`Login` probably doesn't do any SQL writing operations but JWT generation is not the cheapest operation as well.

> I have a feeling but the function that needs to validate the Token has a much higher response time than the function that doesn't need to authenticate, please help me.

I think, authentication makes a small contribution in total time of `createUser` comparing to SQL inserts. Also, it is interesting how much time takes password hashing.

It would be more informative to compare times of GraphQL operations of one type: 2 queries or 2 mutations. To evaluate authentication time you can try to execute the same operation with and without a `roleGuard`.
